apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-two
  namespace: flask-app-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-two
  template:
    metadata:
      labels:
        app: flask-app-two
    spec:
      containers:
      - name: flask-app-two-container
        image: manrala/flaskapptwo:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-two-svc
  namespace: flask-app-two
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: flask-app-two
